stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r * public
    - rm -f public/.gitlab-ci.yml
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
